server:
  port: 7003

spring:
  application:
    name: dbaas-eureka-server

eureka:
  client:
    #是否将自己注册到Eureka Server
    register-with-eureka: true
    #是否从Eureka Server获取注册信息
    fetch-registry: true
    serviceUrl:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/
  instance:
#    prefer-ip-address: false
    hostname: peer3